language: ruby
cache: 
  - bundler
  - yarn
services:
  - postgresql
before_script:
  - yarn
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  